### ISSUE TITLE
安卓8.0 行为变更

### ISSUE THREAD

**Issue by wenjie366** [LightingContour/Toucher#2]
### 使用 SYSTEM_ALERT_WINDOW 权限的应用无法再使用以下窗口类型来在其他应用和系统窗口上方显示提醒窗口：
TYPE_PHONE
TYPE_PRIORITY_PHONE
TYPE_SYSTEM_ALERT
TYPE_SYSTEM_OVERLAY
TYPE_SYSTEM_ERROR
相反，应用必须使用名为 TYPE_APPLICATION_OVERLAY 的新窗口类型。

因此，createToucher中的这行代码应该更改为：
```java
        //设置type.系统提示型窗口，一般都在应用程序窗口之上.
        params.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
```  

谢谢你的博文和源码分享:+1:

**Comment by LightingContour** [comment]
感谢指正！

一年前的代码了，会找个时间去更新下哈哈

**Comment by LightingContour** [comment]
> ### 使用 SYSTEM_ALERT_WINDOW 权限的应用无法再使用以下窗口类型来在其他应用和系统窗口上方显示提醒窗口：
> TYPE_PHONE
> TYPE_PRIORITY_PHONE
> TYPE_SYSTEM_ALERT
> TYPE_SYSTEM_OVERLAY
> TYPE_SYSTEM_ERROR
> 相反，应用必须使用名为 TYPE_APPLICATION_OVERLAY 的新窗口类型。
> 
> 因此，createToucher中的这行代码应该更改为：
> 
> ```java
>         //设置type.系统提示型窗口，一般都在应用程序窗口之上.
>         params.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
> ```
> 
> 谢谢你的博文和源码分享👍

你好，我这里试了下，用的华为EMUI8.0，Android8.0版本，没有出现异常。
请问你这里的机型和系统是？

**Comment by wenjie366** [comment]
抱歉，回复的晚了。很巧的是我现在就在华为实习，当时用的测试机的系统是EMUI 8.1，安卓8.1(SDK version 27)。当时出现了该问题后，我便查阅了[官网文档](https://developer.android.com/about/versions/oreo/android-8.0-changes#o-apps)

**Comment by LightingContour** [comment]
收到。

哈哈华为的手机确实好用，不过我自己用的Mate8，更新到8.0已经是极限。
这几天试下后就会改下代码。得重新拉一下了

多谢反馈~

**Comment by LightingContour** [comment]
已更新适配
Thanks~
